apiVersion: v1
data:
  config.json: |-
    {
      "inbounds": [
        {
          "port": 10000,
          "listen":"127.0.0.1",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": {{ .Values.app.uuid }},
                "alterId": 0
              }
            ]
          },
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
            "path": "/ray"
            }
          }
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
kind: ConfigMap
metadata:
  labels: 
  {{- include "proxy.labels" . | nindent  4 }}
  name: {{ include "proxy.fullname" . }}
  namespace: {{ .Values.namespace }}