apiVersion: v1
data:
  config.json: |-
    {
      "inbounds": [
        {
          "port": 10000,
          "listen": "127.0.0.1",
          "protocol": "vmess",
          "settings": {
            "clients": [
              {
                "id": {{ .Values.v2ray.uuid | toJson | quote}},
                "alterId": 0
              }
            ]
          },
          {{- if contains "ws" .Values.v2ray.streamSettings.network }}
          "streamSettings": {
            "network": "ws",
            "wsSettings": {
              "path": "/ray"
            }
          }
          {{- else if contains "http" .Values.v2ray.streamSettings.network }}
          "streamSettings": {
          "network": "tcp",
          "tcpSettings": {
            "header": {
              "type": "http",
              "response": {
                "version": "1.1",
                "status": "200",
                "reason": "OK",
                "headers": {
                  "Content-Type": ["application/octet-stream", "application/x-msdownload", "text/html", "application/x-shockwave-flash"],
                  "Transfer-Encoding": ["chunked"],
                  "Connection": ["keep-alive"],
                  "Pragma": "no-cache"
                }
              }
            }
          }
          {{- end }}
        }
      ],
      "outbounds": [
        {
          "protocol": "freedom",
          "settings": {}
        }
      ]
    }
kind: ConfigMap
metadata:
  labels: 
  {{- include "v2ray.labels" . | nindent  4 }}
  name: {{ include "v2ray.fullname" . }}
  namespace: {{ .Values.namespace }}